### ISSUE TITLE
Subscription duplication

### ISSUE THREAD

**Issue by valerybugakov** [rmosolgo/graphql-streaming#3]
I've used code from examples:
```rb
context[:subscriber] = GraphQL::Streaming::ActionCableSubscriber.new(self, query_id) do
  ClientSchema.execute(query_string, variables: variables, context: context)
end
```
Here if I have `subscriber` in the context every time query is reevaluated subscriber will be registered again. 
```rb
def call(obj, args, ctx)
  subscriber = ctx[:subscriber]
  subscriber && subscriber.register(@subscription_handle, args.to_h)
  resolve(obj, args, ctx)
end
```
So I've added `context.delete(:subscriber)` to the resolve function:
```rb
context[:subscriber] = GraphQL::Streaming::ActionCableSubscriber.new(self, query_id) do
  context.delete(:subscriber)
  ClientSchema.execute(query_string, variables: variables, context: context)
end
```
Is it how it's supposed to work?

**Comment by rmosolgo** [comment]
Hmm let's see if I remember ... 

I think it was supposed to work with the [stream_graphql_query](https://github.com/rmosolgo/graphql-streaming#subscriber) helper which yields a context. 

That way, during the first call, a subscriber is present in the context (https://github.com/rmosolgo/graphql-streaming/blob/master/lib/graphql/streaming/action_cable_channel.rb#L45-L50), but in later calls, no subscriber is present (https://github.com/rmosolgo/graphql-streaming/blob/master/lib/graphql/streaming/action_cable_channel.rb#L35-L40)

It's been a while since I tinkered with this project, but I'm hoping to revisit subscriptions soon since the specification is coming together!

**Comment by valerybugakov** [comment]
@rmosolgo oh, I've reimplemented this helper in my code. I see now, thanks!
